#!/bin/bash

termiantor='\033[0m'

color_code=0
bold_code=0
# would be better to use getopts
# see http://mywiki.wooledge.org/BashFAQ/035#getopts
while :
do
	case $1 in
		r  |  red)		color_code=31; shift;;
		g  |  green)	color_code=32; shift;;
		# br |  brown)	color_code=33; shift;;
		y  | yellow)	color_code=33; shift;;	# this is actually brown, but it look yellow to me
		b  |  blue)		color_code=34; shift;;
		p  |  purple)	color_code=35; shift;;
		c  |  cyan)		color_code=36; shift;;
		-b | --bold)	bold_code=1; shift;;
		*)				break;; # no more options. break the loop
	esac
done

color="\033[$bold_code; $color_code m"

while read line; do
	echo -e $color$line$termiantor
done
